---
name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  # To avoid uploading the Docker image to a registry yet
  # the image is built here & immediately used to test all exercises in.
  # TODO at a later point split that into separate jobs
  build_image_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker image build --tag esp --file .devcontainer/Dockerfile .

      - name: Test code examples in Docker image
        run: docker run --user esp --mount type=bind,source="$(pwd)",target=/home/esp/workspace,consistency=cached --rm -it esp:latest /bin/bash /home/esp/workspace/.devcontainer/test.sh